BCLab-UNM/SwarmBaseCode-ROS

.gitignore, simulation/models/achilles/model.sdf, simulation/models/aeneas/model.sdf, simulation/models/ajax/model.sdf, simulation/models/diomedes/model.sdf, simulation/models/hector/model.sdf, simulation/models/paris/model.sdf, simulation/models/thor/model.config, simulation/models/thor/model.sdf, simulation/models/zeus/model.config, simulation/models/zeus/model.sdf
updated rover model files with bumper collision boxes
The problem:
The rovers keep driving up on top of cubes, which deviates from
the normal behaviour found in physical rovers.
The solution:
Bumper collision boxes have been added in front of the wheels to
prevent them from riding on top of cubes and getting stuck.
=> Hotfix 1.3.5 alpha

src/behaviours/src/DriveController.h, src/sbridge/src/sbridge.cpp
sBrdige would not map speeds correctly and the max speed was to low for rotation
This has been corrected to allow 4.5 radians per second and 0.6 m/s for respective movments and roughly mapping -255 - +255 onto -4.5 - +4.5 for rotation and the equivalent for linear
Also the maximum alignment error was increased by 0.05 radians to prevent possible oscilliaions.
Known additonal bug, robot may seem to freeze on rare occasion biased towards the start of sim but it will eventually turn to correct heading and drive.
=> Fixed simulation not driving like real rovers

src/rqt_rover_gui/src/MapData.cpp, src/rqt_rover_gui/src/MapData.h, src/rqt_rover_gui/src/MapFrame.cpp, src/rqt_rover_gui/src/MapFrame.h, src/rqt_rover_gui/src/rover_gui_plugin.cpp, src/rqt_rover_gui/src/rover_gui_plugin.h, src/rqt_rover_gui/src/rover_gui_plugin.ui
First, a disclaimer and apology: the single massive commit is the
result of having to cherry pick the many apsects of this feature
from other branches that were merged or partially merged into the
now-deleted development branch.
That being said, there is a lot of really cool things in this feature:
- Unique Rover Colors: You can check this box on the sensor display
tab to have reach rover's trail on the Map Frame be uniquely
colored. There are 8 unique colors, if you are using more than
8 rovers than the colors are assigned in a cycle. For example,
rover 0 and rover 8 will be the same color, etc.
- Global Frame: You can check this box on the sensor display tab to
reposition the Map Frame trails of all rovers to be as they appear
in the Gazebo world. That is, the Map Frame displays all …
=> significant improvements and streamlining to the RQT GUI interface

src/rqt_rover_gui/src/MapFrame.cpp
Messages sent from the popout map were not displayed in the GUI info text region. The info log signal from popout_mapframe was not connected to the rover GUI receive info log slot.
The fix was to connect the popout_mapframe signal to the parent mapframe signal. This forwards the info log messages from the popout frame to the parent frame and on to the rover GUI.
=> Bug fix: infolog messages from popout map not displayed

src/rqt_rover_gui/src/MapFrame.cpp
Resolves issue #71 by guarding against empty path lists
This is something that is done implicitly and explicitly throughout
the code, and is necessary here to ensure that we don't try to draw
anything after the map data is cleared on destruction of the gui.
=> Don't crash on close when popout map is open

src/abridge/src/abridge.cpp
A previous update to joystick control brought its output in line with auto mode
This causes the special case in abridge to no longer be needed.
fixes issue #74
=> Fixed manual driving controle for physical rovers

src/abridge/src/abridge.cpp, src/behaviours/src/PickUpController.cpp
Fixed math from pickup to correctly give blockDistance its appropriate values.  Bad math in pickup resulted in a 0 or close to 0 value being given to blockDistance and never allowing the rover to alter orientation
=> Bug pickup math fix

src/behaviours/src/PickUpController.cpp, src/behaviours/src/PickUpController.h
Fixed several key issues:
- Gripper Twitching up and down
- Issue with rovers resetting nTargetsSeen and not taking into account delay differences from Camera and the rovers running code
These 2 issues both stem from the same problem.  There was an issue with nTargetsSeen being reset to 0 before the camera could update.  Added a timer and reset nTargetsSeen after the timer has made up for the delay (6/10th's of a second)
Secondly tuned pickup variables and needs further testing.  Was successfully able to pickup 9/10 cubes within 30 seconds.
Resolves issue #65 , tentatively resolves #60
=> Bug pickup efficiency

README.md
The previous Quick Start Guide link on the README.md was dead (404 error). I have included the live one from the documentations page on the NASA Swarmathon website.
=> Added live Quick Start Guide link on the README.md

misc/deploy.sh
The problem wasn't actually with nested directories. The issue came from missing ublox and april tag submodules. This pull request checks to see if the ublox or april tag submodules are present. If not, it will initialize and update them both. It will then continue with the rest of the script, rather than terminate.
=> Updated deploy script to initialize and update submodules

src/behaviours/CMakeLists.txt, src/rqt_rover_gui/CMakeLists.txt
Added explicit dependencies on swarmie_msgs otherwise the headers may not be generated in time for the GUI and behaviours packages to find them.
=> Bug fix: swarmie message dependency declarations missing

src/rqt_rover_gui/src/rover_gui_plugin.cpp, src/rqt_rover_gui/src/rover_gui_plugin.ui
This pull request addresses several minor issues at once:
- commit: 4ea944c
- commit: 881e7a3
- commit: 721d95c
- commit: 879c12a
=> Hotfix minor gui bugs

README.md, misc/deploy.sh
Removed lingering code in -R section.  
Fixed error in check command from previous commit. 
Fixed issue in run where wouldn't exit when typing exit. 
Cleaned up user options prompt when running rovers in all options (fix for #101).  
Finished ability to run script from command line without the use of the interface. (fix #102)
- Typing -N will now not run the GUI and run everything and return back to the command terminal
+ ex:  ./deploy.sh -R -N r05
Need to still update the README and some internal script documentation.  Please check to see if this is working as I correct this.
Thanks!
=> Fixed Multiple Bugs for Startup Script

src/rqt_rover_gui/src/MapData.cpp, src/rqt_rover_gui/src/MapData.h, src/rqt_rover_gui/src/MapFrame.cpp, src/rqt_rover_gui/src/MapFrame.h, src/rqt_rover_gui/src/rover_gui_plugin.cpp
Added map to MapData indicating rover modes. When a user clicks in the
map frame we consult that map and if the mode is not manual then the
click is ignored. This addresses issue #116 by simply preventing that
situation.
=> Don't accept manual waypoint input for rover's in autonomous mode

src/rqt_rover_gui/src/rover_gui_plugin.cpp
The obstacle call count will reset only if there are no rovers connected to the GUI. Else, it will continue to count obstacles globally. This fixes issue #93. Also, fixed a typo in the date on the top.
(I created a new pull request because my git config file was registered with Matthew's information.)
=> Reset Obstacle Call Count

src/behaviours/src/DriveController.cpp, src/behaviours/src/PID.cpp, src/behaviours/src/ROSAdapter.cpp
Rovers would get stuck in the ROTATE state of the statemachine inside DriveController.cpp .  The values being passed out of the fastPID method were too low (varied from 40 all the way to 0 or 1).  The net result was the rover would send these through ROSAdapter into sendDriveCommand resulting in constant power to motors but the rover wouldn't move.  The fix was to set a hard min value for rover motor speeds coming out of fastPID inside the ROTATE state.  Currently set to 80 and seems to run ok.  Needs testing.  Made changes to PID.cpp and ROSAdapter.cpp with cleaning up and commenting all 3 files and moving some braces for readability while debugging problem.  Currently left debugging cout statements in code for future hardware testing.  Will remove once testing is complete before pull …
=> Fix for stuck in place rovers

src/diagnostics/src/Diagnostics.cpp, src/diagnostics/src/Diagnostics.h
Removed references to the obstacle node in diagnostics. The code that was in obstacle is now in the behaviours package and the obstacle package has been removed. Diagnostics was still sending error messages to the UI about the absence of obstacle.
=> Hotfix: Obstacle node was still being checked for in diagnostics

src/diagnostics/src/WirelessDiags.cpp
…nostics and call WirelessDiag::calcBitRate() which return corrupt values when variables receive_stat and/or transmit_stat are empty, executes stoi on empty strings. Can replicate bug by adding receive_stat.clear(); and/or transmit_stat.clear(); before calling stoi.
=> Diagnostics error displaying "stoi"

misc/deploy.sh
This make the deploy script actually copy the tarball when in silent mode.
=> Fixed the silent mode of deploy script

misc/deploy.sh
If symlinks are copied as links this will cause broken links on the
rover and may cause the deploy process to fail. Instead we use the -h
flag on tar to replace symlinks with the files they point to.
=> Deploy script should copy symlinks as regular files

src/rqt_rover_gui/src/rover_gui_plugin.cpp
Caused the gripper to twitch when picking up cubes because it was recieving conflicting commands from the joystick.
=> Do not accept manual joystick commands in auto mode

src/behaviours/src/ROSAdapter.cpp
Drift tolerance variable was set to 1.2 meters, Changed to 5 meters as was having negative impact on rover performance.
=> Changed Drift Tolerance to 5 Meters

src/behaviours/src/LogicController.cpp, src/behaviours/src/ManualWaypointController.cpp, src/rqt_rover_gui/src/MapData.cpp
When entering autonomous mode, remove all manual waypoints to stop the rover from driving off on its own when you go back to manual mode.
=> Hotfix reset manual waypoints

src/behaviours/src/ROSAdapter.cpp
The odeometry estimate of the collection zone location is synced with the GPS estimate when they differ by more than 0.5 (previously 5m). This change increases the number of cubes collected by 3 rovers in 30 mins from 1 to 13.
The startup delay has been changed from 15 s to 30 s. This is to give the rovers more time to estimate their initial location using GPS.
=> Make better use of GPS

src/diagnostics/src/Diagnostics.cpp, src/rqt_rover_gui/src/rover_gui_plugin.cpp
This patch fixes the constant erroneous disconnect messages in the GUI. 
It does two things: 
1. Reduce the queue size for diagnostic messages to one. There's no need to queue diagnostic messages because old ones are not useful. 
2. Sets the timestamp of the received message in the GUI to ros::Time::now(). 
The underlying problem seems to be that event.getReceiptTime() returns zero always. This seems like a bug in ROS but it might just be poor documentation. I suspect that in order for this to work the message must be defined to have a std_msgs/Header. At the time scale that matters for diagnostic messages this is good enough.
=> Fix constant erroneous disconnect messages.

misc/deploy.sh, misc/rover_onboard_node_launch.sh
deploy and rover_onboard_node_launch both used a fixed path that would result in issues if SwarmBaseCode-ROS wasn't existing on the rover.  Would cause the rover to refuse to acknowledge tags due to distance always being 0 (rover_onboard_node_launch) and the eploy script only searching for SwarmBaseCode-ROS with the run option.
Jaretts account changed my checkin for me.  :(
Addresses issue #156
=> Changed direct pathing to relative pathing

src/behaviours/src/ROSAdapter.cpp
This fixed the robot getting into an invalid state of operation causing it to no longer respond to cubes if cubes are visible upon first startup
This fixes issue #103
=> Hotfix for invalid start when cube visible

.gitmodules
River Labs AprilTags_ROS is not compatible with OpenCV 3.3.1. This seems to result in a crash in the camera stream. We forked the AprilTags library and fixed the problem. Now we make SwarmBaseCode use the fixed repository.
The problem shows up in sim as a frozen camera.
=> Update AprilTags_ROS submodule to BCLabs-UNM's version

src/rqt_rover_gui/src/MapFrame.cpp
the point is only visible when odom is selected and is displayed in
the same color as the robot's odom track.
=> Added point indicating rover location in odom frame

src/rqt_rover_gui/src/MapFrame.cpp
The Problem:
The GUI would hange and crash un-elegantly when exited with
an active popout window.
The Solution:
In the MapFrame clear() function a call to popout_window->close()
has been added.
When you exit the GUI, the shutdownPlugin() function is called
in the rover_gui_plugin class. This function calls the MapFrame's
clear() function to clear the map and stop drawing before the
map frame is destroyed.
Because we know that this function is called when the GUI is
exiting, we have added an explicit function call to close the
popout_window if and only if it is currently active.
In this way, the window is closed before the rovers are shut
down and the entire crashing/hanging problem is completely
avoided where the popout window is trying to access null data.
=> fixed GUI crash bug when GUI is closed with popout map active

src/rqt_rover_gui/src/GazeboSimManager.cpp
Fixes #187 
Tested multiple start/stop viz scenarios. Ensured that simulated robots respond to auto/manual mode and that  they still collect cubes with/without viz.
=> Assign the name gzclient to the gazebo_ros client node

launch/swarmie.launch
Obstacle was removed a long time ago but the reference is still in swarmie launch. Results in error messages when swarmie launch is used.
=> Bug fix: removed dead reference to obstacle node

src/rqt_rover_gui/src/rover_gui_plugin.ui
The problem:
The default font size in the font size combo box in the GUI
was erroneously set to 5.
The correct default size is actually set to 15. This results
in extremely odd resizing behaviour whenever the user presses
the font resize keys ('-'/'=').
The solution:
The combobox default value was set to 15.
This bug fix is for issue #198
=> fixed a bug where the default font size was incorrectly set

src/rqt_rover_gui/src/IMUFrame.cpp, src/rqt_rover_gui/src/IMUFrame.h
The problem:
The cube representing the IMU data would not scale in size
with changes to the size of the GUI window.
The solution:
The eight (x,y,z) points representing the corners of the cube
stored in the "cube[]" variable are now updated with a new
"width_of_square" value during each paint event.
Also, the coordinates for the lines drawn from the cube are
also updated (line1 and line2).
The caveats:
The initial square drawn when the GUI is launched will NOT
resize... I have been unable to determine why this is the case;
especially since, for example, the ultrasound frame DOES
resize and both class implementations of QFrame are identical.
However, once a rover is selected, the IMU graphic resizes
appropriately.
This pull request addresses issue #200
=> updated the IMU frame to be scalable with the GUI

src/rqt_rover_gui/src/MapFrame.cpp
The problem:
When the simulation or physical rovers are running, and
most specifically when they are running in AUTO mode, using
manual map panning causes the map to seemingly jump to a
random location on left click.
The source of this bug is error checking included with
manual waypoints.
Whenever a left click occurs in the map frame, the variable
"previous_clicked_position" must be updated so that clicking
and panning in the map works properly.
However, this variable is not properly updated when the
robots are in auto mode because manual waypoints error
checking short circuits the function too early.
The solution:
All manual waypoints error checking has been moved into the
if statement handling RIGHT mouse clicks. That is, we will
now always and properly update …
=> fixed map panning bug where clicking jumps to random location

src/rqt_rover_gui/src/rover_gui_plugin.cpp, src/rqt_rover_gui/src/rover_gui_plugin.ui
The problem:
The select custom world button and file path display stay
interactive even after starting a simulation; this behaviour
is undesirable and un-intuitive to how the interaction is
supposed to work.
The solution:
The GUI has been updated to properly disable/enable this button
after clicking "build simulation" and "end simulation".
This pull request addresses issue #142
=> fixed a bug where the custom world button doesn't disable properly

simulation/models/achilles/model.sdf, simulation/models/aeneas/model.sdf, simulation/models/ajax/model.sdf, simulation/models/diomedes/model.sdf, simulation/models/hector/model.sdf, simulation/models/paris/model.sdf, simulation/models/thor/model.sdf, simulation/models/zeus/model.sdf
Addresses issue  #204 
http://gazebosim.org/tutorials/?tut=ros_urdf#Joints
The damping element adds a viscous damping coefficient to oppose the joint velocity. Reducing it speeds up the wrist and finger movements to more realistic speeds.
=> Reduce gripper wrist and finger joint damping values.

src/rqt_rover_gui/src/rover_gui_plugin.cpp
The Problem:
When running timed simulation runs, the obstacle avoidance call
count continues to accumulate for the entire duration of a sim
and not just for a timed run.
The Solution:
In the logic where a timed run is initiated, the obstacle avoidance
count is reset to 0.
=> Added additional logic to reset the obstacle_call_count for timed runs

src/abridge/CMakeLists.txt, src/abridge/package.xml, src/abridge/src/abridge.cpp, src/behaviours/src/ROSAdapter.cpp, src/sbridge/CMakeLists.txt, src/sbridge/package.xml, src/sbridge/src/sbridge.cpp, src/sbridge/src/sbridge.h, src/swarmie_msgs/CMakeLists.txt, src/swarmie_msgs/msg/Skid.msg
Instead of abusing the Twist message we now use a Skid message that
explicitly contains a left motor command and a right motor command.
=> Use a custom message for commanding the robot motors.

launch/swarmie.launch
Addresses issue #233 
This adds the conventional `rovername_` prefix to all the topic_tools throttle nodes started in the simulation launch file.
=> Avoid throttled node name conflicts with rover name prefix

misc/run_calibration.sh
1 second allows for a race condition. This change still allows for a race, but makes it much less likely.
=> Increase pause to allow roscore to start

simulation/models/achilles/model.sdf, simulation/models/aeneas/model.sdf, simulation/models/ajax/model.sdf, simulation/models/diomedes/model.sdf, simulation/models/hector/model.sdf, simulation/models/paris/model.sdf, simulation/models/swarmie/model.sdf.erb, simulation/models/thor/model.sdf, simulation/models/zeus/model.sdf
See PR #243. This pull request supersedes the earlier one since we are using templated model files now. Thanks to @darrenchurchill. 
"I settled on a very small Constraint Force Mixing parameter (0.01), to soften the wheel joints slightly, and a greatly increased the Error Reduction Parameter (0.8), so the wheels move quickly back to their normal positions in just a few physics iterations if they get slightly out of place.
The CFM is small enough so there shouldn't be any 'suspension' effect or vibration in the model when it comes to a stop."
=> Improved wheel dynamics
