- .catkin_tools/profiles/default/packages/behaviours/package.xml
- misc/deploy.sh
- src/abridge/src/abridge.cpp
Created and made the startup script (deploy.sh).
> Startup scripts

- src/behaviours/src/PickUpController.cpp
Still needs tuning for 16.04 sim and is not tuned for physical robots yet but may still work with current settings.
> Fixed pickup routine to be back above a 75% succese rate.

- src/rqt_rover_gui/src/MapFrame.cpp
The merge of the waypoints and GUI improvements feature branches caused problems in the paintEvent function of the MapFrame class. Those problems are fixed in this hotfix.
> Corrected conflicts between waypoints and rover unique colours

- src/rqt_rover_gui/src/MapFrame.cpp
Adding waypoints to the popout map works just like in the regular map.
> Hotfix popout map waypoints

- src/behaviours/src/DriveController.cpp
Don't overshoot waypoints (quite so much) This resolves issue #58 and #92
> Bug waypoint overshoot

- README.md
Includes general documentation for the behaviours package (#95)
> Behaviours documentation

- misc/deploy.sh
- src/behaviours/src/DriveController.cpp
Updated script with a check to ensure the options are typed in correctly, if not to exit the script.  Removed lingering debug code from DriveController.cpp.
> Modified Script and removed Debug Code

- src/rqt_rover_gui/src/MapData.cpp
- src/rqt_rover_gui/src/MapData.h
- src/rqt_rover_gui/src/MapFrame.cpp
- src/rqt_rover_gui/src/MapFrame.h
- src/rqt_rover_gui/src/rover_gui_plugin.cpp
- src/rqt_rover_gui/src/rover_gui_plugin.h
This hotfix corrects several key issues with Manual Waypoints:
- commit: ebeb2b2 
- commit: 28a0b53
- commit: 21bbac7 
- commit: db4fcf4
> Hotfix waypoint bugs

- src/behaviours/src/DriveController.cpp
- src/behaviours/src/DriveController.h
- src/behaviours/src/ObstacleController.cpp
- src/behaviours/src/PID.cpp
- src/behaviours/src/PickUpController.cpp
- src/sbridge/src/sbridge.cpp
:warning: warning PID is functional but still needs some fixing up
> Hotfix pid changes

- src/behaviours/src/ObstacleController.cpp
- src/behaviours/src/ObstacleController.h
needed merge because I accidentally made commit in wrong branch.
> Bug hotfix obstacle avoidance while carrying cube

- src/behaviours/src/PickUpController.cpp
- src/behaviours/src/PickUpController.h
Added some comments to provide a more complete description of what is
going on.
> Updated comments for PickupController.

- src/behaviours/src/DropOffController.cpp
Added more comments for code clarity.
> Dropoff controller comments

- src/behaviours/src/LogicController.cpp
- src/behaviours/src/LogicController.h
Completed updates to comments for the Logic Controller.
There was already an existing amount of comments; most of the work here polishes them and expands on them where necessary.
> Logic controller commenting

- src/behaviours/src/PID.cpp
Added a few more comments for code clarity. The code was already commented pretty well already though.
> Pid comments

- src/behaviours/src/ROSAdapter.cpp
- src/behaviours/src/Tag.cpp
Commenting for ROS adapter and Tag.h and tag.cpp
Let me know if anything needs to be changed.
@JCHJones I have a few issues with ??? in comments if you could give me a hand with those.  Thanks!
- Jeff
> Ros adapter tag commenting

- src/sbridge/src/sbridge.cpp
- src/sbridge/src/sbridge.h
Added comments for code clarity.
> Sbridge comments

- .travis.yml
This yaml file configures compilation testing on push.
> Added travis testing

- src/rqt_rover_gui/src/GazeboSimManager.cpp
- src/rqt_rover_gui/src/rover_gui_plugin.cpp
- src/rqt_rover_gui/src/rover_gui_plugin.h
- src/rqt_rover_gui/src/rover_gui_plugin.ui
The GUI has been re-factored to be scalable.
- The main program window is re-sizable.
- The font size of text in the GUI is manually re-sizable using the "-" and "=" keyboard keys.
- Frames can be toggled on/off (i.e. you can disable frames so the user only sees frames they want).
- GUI elements have been reorganized to facilitate a scalable window.
> Implement scalable gui

- README.md
A step in the qtcreator setup was missing.
> Added missing instruction

- .travis.yml
- run_headless_sim.sh
- run_tests.sh
Allows the gazebo simulation to be run without the GUI. This means we can run the simulations headless, particularly on HPC clusters.
> Headless sim

- src/behaviours/src/LogicController.cpp
- src/behaviours/src/LogicController.h
- src/behaviours/src/ROSAdapter.cpp
The collision time displays in the GUI correctly
> Update the collision avoidance call

- src/rqt_rover_gui/src/rover_gui_plugin.cpp
- src/rqt_rover_gui/src/rover_gui_plugin.ui
This pull request adds radio buttons to the GUI to toggle between the physical barriers or the AprilTag boundaries.
It replaces the temporary fix introduced in #217
> Implement gui apriltag fence option

- launch/swarmie.launch
- misc/rosbridge/swarmie.js
- misc/rover_launch_local.sh
- misc/rover_onboard_node_launch.sh
- misc/start_robots.sh
- src/rqt_rover_gui/src/rover_gui_plugin.cpp
> Throttle by default

- misc/rosbridge/swarmie.js
- src/behaviours/CMakeLists.txt
- src/behaviours/src/LogicController.cpp
- src/behaviours/src/LogicController.h
- src/behaviours/src/PositionPublisher.cpp
- src/behaviours/src/PositionPublisher.hpp
- src/behaviours/src/ROSAdapter.cpp
- src/behaviours/src/SearchController.cpp
- src/behaviours/src/SearchController.h
- src/swarmie_msgs/CMakeLists.txt
- src/swarmie_msgs/msg/Recruitment.msg
Demo of simple recruitment plus integration with rosbridge shim.
> Recruitment demo

- misc/rosbridge/swarmie.js
- src/behaviours/src/ROSAdapter.cpp
- src/rqt_rover_gui/src/rover_gui_plugin.cpp
Changed the rover's /status topic to /swarmie_status to avoid any
conflicts with the ROS Actionlib framework
> Ref #220: gui-status-topic update

- recruitment-demo.md
Added tutorial in markdown form to repository root.
> tutorial describing a recruitment demonstration

- run_headless_sim.sh
> run_headless_sim.sh: Fixed publishing all stop from string to UInt8

- misc/rover_onboard_node_launch.sh
- misc/start_robots.sh
Correct two bugs in the startup scripts
> Fix startup bridged
